# SwiftLint Configuration for Icons Project

# 包含的文件路径
included:
  - Icons/
  - IconsTests/
  - IconsUITests/

# 排除的文件路径
excluded:
  - Icons.xcodeproj
  - build/
  - .build/
  - DerivedData/
  - .trae/

# 禁用的规则
disabled_rules:
  - trailing_whitespace  # 允许行尾空格（在某些情况下有用）
  - todo                 # 允许 TODO 注释
  - line_length         # 使用自定义行长度规则

# 启用的可选规则
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 自定义规则配置
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration

# 行长度配置
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# 文件长度配置
file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

# 函数长度配置
function_body_length:
  warning: 50
  error: 100

# 类型长度配置
type_body_length:
  warning: 200
  error: 300

# 函数参数数量配置
function_parameter_count:
  warning: 5
  error: 8

# 大型元组配置
large_tuple:
  warning: 3
  error: 4

# 嵌套类型级别配置
nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

# 标识符名称配置
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z
    - dx
    - dy
    - dz
    - i
    - j
    - k
    - vm  # ViewModel 缩写
    - ui  # User Interface 缩写
    - ai  # Artificial Intelligence 缩写
    - sf  # SF Symbols 缩写
    - url
    - api

# 类型名称配置
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL
    - API
    - UI
    - AI
    - SF

# 文件头部注释配置
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Icons
                    \/\/
                    \/\/  Created by .* on \d{4}\/\d{1,2}\/\d{1,2}\.
                    \/\/

# 强制解包配置
force_unwrapping:
  severity: warning

# 隐式返回配置
implicit_return:
  included:
    - closure
    - function
    - getter

# 修饰符顺序配置
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

# 垂直空白配置
vertical_whitespace:
  max_empty_lines: 2

# 自定义规则
custom_rules:
  # 禁止使用 print() 在生产代码中
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    match_kinds:
      - comment
      - string
    message: "Use proper logging instead of print statements"
    severity: warning
  
  # 确保 TODO 注释包含作者信息
  todo_author:
    name: "TODO Author"
    regex: "TODO(?!.*\\(.*\\))"
    message: "TODO should include author name in parentheses"
    severity: warning
  
  # 确保 FIXME 注释包含作者信息
  fixme_author:
    name: "FIXME Author"
    regex: "FIXME(?!.*\\(.*\\))"
    message: "FIXME should include author name in parentheses"
    severity: warning
  
  # 禁止使用强制类型转换
  no_force_cast:
    name: "No Force Cast"
    regex: "as!"
    message: "Use safe casting with 'as?' instead of force casting 'as!'"
    severity: error
  
  # 确保异步函数使用 async/await
  async_await_usage:
    name: "Async Await Usage"
    regex: "DispatchQueue\.main\.async"
    message: "Consider using async/await instead of DispatchQueue.main.async"
    severity: warning

# 报告器配置
reporter: "xcode"

# 严格模式（将警告视为错误）
strict: false

# 排除特定文件的特定规则
excluded_rules_in_files:
  # 在测试文件中允许强制解包
  force_unwrapping:
    - "*Tests.swift"
    - "*Test.swift"
  
  # 在预览文件中允许较长的函数
  function_body_length:
    - "*Preview.swift"
    - "*Previews.swift"